# Homework for Week 3

## Dataset

The dataset will used is :

In [4]:
# Import the relevant libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
# link = "https://archive.ics.uci.edu/static/public/222/bank+marketing.zip"
# !wget $link

In [6]:
# Preview of dataset
df = pd.read_csv('data/bank_full.csv', delimiter=";")
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

The columns used are:
- `age`
- `job`
- `marital`
- `education`
- `balance`
- `housing`
- `contact`
- `day`
- `month`
- `duration`
- `campaign`
- `pdays`
- `previous`
- `poutcome`
- `y`

## Data Preparation

In [9]:
# The columns used only
features = ['age', 'job', 'marital', 'education', 'balance', 
            'housing', 'contact', 'day', 'month', 'duration', 
            'campaign', 'pdays', 'previous', 'poutcome', 'y']

In [10]:
df[features].isnull().sum()

age          0
job          0
marital      0
education    0
balance      0
housing      0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

No missing value presented on this dataset

In [12]:
df_used = df[features]

## Q1: Check the most frequent on `education`

In [14]:
df_used.education.mode()

0    secondary
Name: education, dtype: object

The most frequent on education is `secondary`

## Q2: Create corelation matrix

In [17]:
from sklearn.metrics import mutual_info_score

age_balance = np.corrcoef(df_used.age, df_used.balance)
day_campaign = np.corrcoef(df_used.day, df_used.campaign)
day_pdays = np.corrcoef(df_used.day, df_used.pdays)
pdays_previous = np.corrcoef(df_used.pdays, df_used.previous)

age_balance, day_campaign, day_pdays, pdays_previous

(array([[1.        , 0.09778274],
        [0.09778274, 1.        ]]),
 array([[1.        , 0.16249022],
        [0.16249022, 1.        ]]),
 array([[ 1.        , -0.09304407],
        [-0.09304407,  1.        ]]),
 array([[1.        , 0.45481964],
        [0.45481964, 1.        ]]))

The biggest correlation is between `pdays` and `previous`

## Encoding the target

In [20]:
df_used.y = (df_used.y == 'yes')
df_used.head()

C:\Users\Rafiq Ramadhan\AppData\Local\Temp\ipykernel_1728\106750611.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_used.y = (df_used.y == 'yes')


age           job  marital  education  balance housing  contact  day month  \
0   58    management  married   tertiary     2143     yes  unknown    5   may   
1   44    technician   single  secondary       29     yes  unknown    5   may   
2   33  entrepreneur  married  secondary        2     yes  unknown    5   may   
3   47   blue-collar  married    unknown     1506     yes  unknown    5   may   
4   33       unknown   single    unknown        1      no  unknown    5   may   

   duration  campaign  pdays  previous poutcome      y  
0       261         1     -1         0  unknown  False  
1       151         1     -1         0  unknown  False  
2        76         1     -1         0  unknown  False  
3        92         1     -1         0  unknown  False  
4       198         1     -1         0  unknown  False

## Split the data

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
df_full_train, df_test = train_test_split(df_used, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [24]:
df_train

age            job   marital  education  balance housing   contact  \
20326   32     technician    single   tertiary     1100     yes  cellular   
24301   38   entrepreneur   married  secondary        0     yes  cellular   
38618   49    blue-collar   married  secondary     3309     yes  cellular   
18909   37      housemaid   married    primary     2410      no  cellular   
23081   31  self-employed   married   tertiary     3220      no  cellular   
...    ...            ...       ...        ...      ...     ...       ...   
13264   27       services    single  secondary      167      no  cellular   
28829   40     technician    single   tertiary      693      no  cellular   
3844    54     technician  divorced  secondary        0     yes   unknown   
15597   25       services    single  secondary     2311      no  cellular   
22987   30     management    single   tertiary       15      no  cellular   

       day month  duration  campaign  pdays  previous poutcome      y  
20326   11   aug        67         1     -1         0  unknown  False  
24301   17   nov       258         1     -1         0  unknown  False  
38618   15   may       349         2     -1         0  unknown  False  
18909    4   aug       315         1     -1         0  unknown  False  
23081   26   aug        74         4     -1         0  unknown  False  
...    ...   ...       ...       ...    ...       ...      ...    ...  
13264    8   jul       606         2     -1         0  unknown  False  
28829   30   jan       427         1     -1         0  unknown  False  
3844    16   may       161         1     -1         0  unknown  False  
15597   21   jul      1105         2     -1         0  unknown   True  
22987   26   aug       252         2     -1         0  unknown  False  

[27126 rows x 15 columns]

In [25]:
df_train = df_train.reset_index()
df_val = df_val.reset_index()
df_test = df_test.reset_index()

y_train = df_train.y
y_val = df_val.y
y_test = df_test.y

## Q3: Mutual Information Score

In [27]:
from sklearn.metrics import mutual_info_score

In [28]:
def mutual_info_y_score(series):
    return mutual_info_score(series, df_train.y)

In [29]:
categorical = ['job', 'marital', 'education', 'housing', 'contact', 'month', 'poutcome']

In [30]:
mi = df_train[categorical].apply(mutual_info_y_score)
mi = mi.round(3)
mi.sort_values(ascending=False)

poutcome     0.030
month        0.025
contact      0.013
housing      0.010
job          0.007
education    0.003
marital      0.002
dtype: float64

The biggest score is `poutcome` with `0.03`. I used rounding into 3 digits instead of two, cause `poutcome` and `month` will round into the same number `0.03`, more accurate using 3 digits.

## Q4: Logistic Regression

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction import DictVectorizer

In [34]:
del df_train['y']
del df_val['y']
del df_test['y']

In [35]:
def train(df, y, C=1.0, max_iter=1000, random_state=42):
    train_dicts = df.to_dict(orient='records')
    dv = DictVectorizer(sparse=False)
    X_train = dv.fit_transform(train_dicts)

    model = LogisticRegression(solver='liblinear', C=C, max_iter=max_iter, random_state=random_state)
    model.fit(X_train, y)
    
    return dv, model

In [36]:
def predict(dv, model, df, y):
    test_dicts = df.to_dict(orient='records')
    X_test = dv.transform(test_dicts)

    y_pred = model.predict_proba(X_test)[:,1]

    y_decision = (y_pred >= 0.5)
    score = (y == y_decision).mean()

    return score, y_pred

In [37]:
dv, model = train(df_train, y_train)

In [38]:
score_all, y_pred = predict(dv, model, df_val, y_val)
score_all

0.8942711789427118

## Q5: Find the smallest impact feature

In [40]:
features

['age',
 'job',
 'marital',
 'education',
 'balance',
 'housing',
 'contact',
 'day',
 'month',
 'duration',
 'campaign',
 'pdays',
 'previous',
 'poutcome',
 'y']

In [41]:
feature_used = ['age', 'job', 'marital', 'education', 'balance', 'housing',
                'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 
                'previous', 'poutcome']

In [78]:
for n in range(len(feature_used)):
    list_features = feature_used[:n] + feature_used[n+1:]
    dv, model = train(df_train[list_features], y_train)
    score, y_pred = predict(dv, model, df_val[list_features], y_val)

    print(f'remove {feature_used[n]}, with accuracy {score}, with difference using all features {(score - score_all).round(3)}')

remove age, with accuracy 0.9002433090024331, with difference using all features 0.006
remove job, with accuracy 0.9011280690112807, with difference using all features 0.007
remove marital, with accuracy 0.9012386640123866, with difference using all features 0.007
remove education, with accuracy 0.9010174740101747, with difference using all features 0.007
remove balance, with accuracy 0.9006856890068569, with difference using all features 0.006
remove housing, with accuracy 0.9010174740101747, with difference using all features 0.007
remove contact, with accuracy 0.900353904003539, with difference using all features 0.006
remove day, with accuracy 0.9001327140013271, with difference using all features 0.006
remove month, with accuracy 0.8999115239991152, with difference using all features 0.006
remove duration, with accuracy 0.8901791639017916, with difference using all features -0.004
remove campaign, with accuracy 0.9007962840079629, with difference using all features 0.007
remove pd

the smallest impact to the model is `poutcome` with the difference is `-0.0001` 

## Q6: Regularization

In [45]:
C = [0.01, 0.1, 1, 10, 100]

for num in C:
    dv, model = train(df_train, y_train, C=num)
    score, y_pred = predict(dv, model, df_val, y_val)

    print(f'{num}\t: {score.round(3)}')

0.01	: 0.894
0.1	: 0.894
1	: 0.894
10	: 0.895
100	: 0.894
